// ACTION
export const UTC_TIME_AQUIRED = 'UTC_TIME_AQUIRED'
export const LOCAL_TIMEZONE_AQUIRED = 'LOCAL_TIMEZONE_AQUIRED'
export const SEARCH_RESULT_FETCHED = 'SEARCH_RESULT_FETCHED'
export const NEAR_CITIES_FETCHED = 'NEAR_CITIES_FETCHED'
export const CITY_ADDED = 'CITY_ADDED'
export const CITY_REMOVED = 'CITY_REMOVED'


